/*
 * bench_ternary_c.c — host benchmark for the C ternary MAC kernel.
 *
 * Compile:
 *   gcc -O2 -march=native -o bench_ternary_c bench_ternary_c.c
 *
 * Reports ns/op for two C kernels:
 *   1. LUT-based mac (matches firmware/neural/ternary_mac.c W2A6 path)
 *   2. Branchless mac (Path 1 from C reference — same algorithm Rust uses)
 *
 * Inputs are generated by a deterministic xorshift PRNG so the Rust and C
 * benchmarks see identical data and identical accumulators across runs.
 */
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#define N_ITERATIONS 100000000UL  /* 100M MAC bytes (= 400M ternary MACs) */
#define ARRAY_SIZE   (1024 * 1024)

/* ---- Deterministic xorshift PRNG, same seed both langs. ---- */
static uint64_t prng_state = 0x4C4D5141DEADBEEFULL; /* "LMQA" + DEADBEEF */
static inline uint64_t prng_next(void) {
    uint64_t x = prng_state;
    x ^= x << 13; x ^= x >> 7; x ^= x << 17;
    prng_state = x;
    return x;
}

/* ---- LUT-based MAC (matches firmware/neural/ternary_mac.c). ---- */
static const int32_t TERNARY_LUT[4] = {0, 1, -1, 0};

static inline int32_t mac_byte_lut(uint8_t packed_w, const int16_t* act) {
    int32_t acc = 0;
    acc += (int32_t)act[0] * TERNARY_LUT[(packed_w     ) & 0x03];
    acc += (int32_t)act[1] * TERNARY_LUT[(packed_w >> 2) & 0x03];
    acc += (int32_t)act[2] * TERNARY_LUT[(packed_w >> 4) & 0x03];
    acc += (int32_t)act[3] * TERNARY_LUT[(packed_w >> 6) & 0x03];
    return acc;
}

/* ---- Branchless MAC (matches the Rust mac_byte_fast). ---- */
static inline int32_t mac_byte_fast(uint8_t packed_w, const int16_t* act) {
    int32_t acc = 0;
    for (int i = 0; i < 4; i++) {
        int32_t w = (packed_w >> (i * 2)) & 0x03;
        int32_t a = (int32_t)act[i];
        int32_t neg = -(w >> 1);
        int32_t val = (a ^ neg) - neg;
        int32_t nonzero = (w & 1) ^ (w >> 1);
        acc += val & -nonzero;
    }
    return acc;
}

static inline double elapsed_ns(struct timespec* a, struct timespec* b) {
    return (b->tv_sec - a->tv_sec) * 1e9 + (b->tv_nsec - a->tv_nsec);
}

int main(void) {
    /* Pre-generate deterministic input set. */
    int16_t* acts = malloc(sizeof(int16_t) * ARRAY_SIZE);
    uint8_t* packs = malloc(sizeof(uint8_t) * (ARRAY_SIZE / 4));
    for (size_t i = 0; i < ARRAY_SIZE; i++) {
        acts[i] = (int16_t)(prng_next() & 0xFFFF);
    }
    /* Each packed byte: encode 4 weights in {0,1,-1,0} so no 0b11 escape. */
    for (size_t i = 0; i < ARRAY_SIZE / 4; i++) {
        uint64_t r = prng_next();
        uint8_t b = 0;
        for (int j = 0; j < 4; j++) {
            uint8_t w = (r >> (j * 8)) & 0x03;
            if (w == 0x03) w = 0x00; /* keep ternary set */
            b |= (w << (j * 2));
        }
        packs[i] = b;
    }

    /* Warmup. */
    volatile int32_t sink = 0;
    for (size_t i = 0; i < 1000; i++) {
        sink ^= mac_byte_lut(packs[i & 0xFFFF], &acts[(i * 4) & 0x3FFFC]);
    }

    /* ---- LUT bench ---- */
    struct timespec t0, t1;
    int32_t lut_acc = 0;
    clock_gettime(CLOCK_MONOTONIC, &t0);
    for (uint64_t i = 0; i < N_ITERATIONS; i++) {
        size_t pi = i & ((ARRAY_SIZE / 4) - 1);
        size_t ai = (i * 4) & (ARRAY_SIZE - 4);
        lut_acc += mac_byte_lut(packs[pi], &acts[ai]);
    }
    clock_gettime(CLOCK_MONOTONIC, &t1);
    double lut_ns_total = elapsed_ns(&t0, &t1);
    double lut_ns_per   = lut_ns_total / (double)N_ITERATIONS;
    double lut_macs_per = N_ITERATIONS * 4.0 / (lut_ns_total / 1e9) / 1e9;

    /* ---- Branchless bench ---- */
    int32_t fast_acc = 0;
    clock_gettime(CLOCK_MONOTONIC, &t0);
    for (uint64_t i = 0; i < N_ITERATIONS; i++) {
        size_t pi = i & ((ARRAY_SIZE / 4) - 1);
        size_t ai = (i * 4) & (ARRAY_SIZE - 4);
        fast_acc += mac_byte_fast(packs[pi], &acts[ai]);
    }
    clock_gettime(CLOCK_MONOTONIC, &t1);
    double fast_ns_total = elapsed_ns(&t0, &t1);
    double fast_ns_per   = fast_ns_total / (double)N_ITERATIONS;
    double fast_macs_per = N_ITERATIONS * 4.0 / (fast_ns_total / 1e9) / 1e9;

    printf("=== C ternary MAC bench (N=%lu byte-MACs = %lu ternary MACs) ===\n",
           N_ITERATIONS, N_ITERATIONS * 4);
    printf("LUT path        : %.2f ns/byte    %.2f Gmac/s   acc=%d\n",
           lut_ns_per, lut_macs_per, lut_acc);
    printf("Branchless path : %.2f ns/byte    %.2f Gmac/s   acc=%d\n",
           fast_ns_per, fast_macs_per, fast_acc);

    if (lut_acc != fast_acc) {
        fprintf(stderr, "MISMATCH between LUT and branchless paths\n");
        return 1;
    }

    free(acts); free(packs);
    return 0;
}
